### ISSUE TITLE
Timer() issue

### ISSUE THREAD

**Issue by SuzukiHonoka** [dgzlopes/tcp-latency#1]
Please consider to use time.time() instead of timer ().
Thank you for sharing your code!!

**Comment by SuzukiHonoka** [comment]
🙄

**Comment by dgzlopes** [comment]
Hi @SuzukiHonoka! I'm really sorry. Somehow I missed this issue on my GitHub notifications mess.

Thank you **a lot** for creating the issue and pointing this out. I'm not sure if you're still interested, but I removed the `timer()` code in favor of `time.time()` (as you proposed!).

You can see the pull request [here](https://github.com/dgzlopes/tcp-latency/pull/4).
