### ISSUE TITLE
Fix link on the readme

### ISSUE THREAD

**Issue by dgzlopes** [dgzlopes/tcp-latency#10]
On the [similar tools](https://github.com/dgzlopes/tcp-latency#similar-tools) section, `yahoo/serviceping` points to the wrong repo.

**Comment by felipedotcom** [comment]
Can i work on this one?

Done :+1:

**Comment by faisalgunanda** [comment]
can i take this one?

**Comment by dgzlopes** [comment]
Thanks for your time guys! Closing.
